In [1]:
import pandas as pd

In [7]:
import pandas as pd
import warnings
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
plt.style.use('fivethirtyeight')
warnings.filterwarnings('ignore')

#### 각 날짜의 1시간 전의 기상상황을 가지고 1시간 후의 따릉이 대여수를 예측해보세요. 

[Data fields] <br>
① train.csv - 서울시 날짜에 따른 시간별 기상상황과 따릉이 대여 수 (기간: 2017년 4월, 5월)
 <br>
id : 날짜와 시간별 id <br>
temperature : 기온 <br>
precipitation : 비가 오지 않았으면 0, 비가 오면 1 <br>
windspeed : 풍속(평균) <br>
humidity : 습도 <br>
visibility : 시정(視程), 시계(視界)(특정 기상 상태에 따른 가시성을 의미) <br>
ozone : 오존 <br>
pm10 : 미세먼지(머리카락 굵기의 1/5에서 1/7 크기의 미세먼지) <br>
pm2.5 : 미세먼지(머리카락 굵기의 1/20에서 1/30 크기의 미세먼지) <br>
count : 시간에 따른 따릉이 대여 수 <br>
 <br>
③ submission.csv : submission 파일의 예시 <br>
id : 날짜와 시간별 id <br>
count : 예측한 대여 수 기입 <br> 

In [122]:
train = pd.read_csv('train_final.csv') # 판다스를 이용해 csv 파일을 읽어와 train 변수에 저장

test = pd.read_csv('test_final.csv') # 판다스를 이용해 csv 파일을 읽어와 train 변수에 저장

In [123]:
train.columns

Index(['id', 'hour', 'hour_bef_temperature', 'hour_bef_precipitation',
       'hour_bef_windspeed', 'hour_bef_humidity', 'hour_bef_visibility',
       'hour_bef_ozone', 'hour_bef_pm10', 'hour_bef_pm2.5', 'count'],
      dtype='object')

In [124]:
#train['temp_humid'] = train['hour_bef_temperature']/train['hour_bef_humidity']  #Feature Engineering 시도
train['visibility_pm10'] = train['hour_bef_visibility']/train['hour_bef_pm10']
#train['visibility_pm2.5'] = train['hour_bef_visibility']/train['hour_bef_pm2.5']

In [125]:
train.columns

Index(['id', 'hour', 'hour_bef_temperature', 'hour_bef_precipitation',
       'hour_bef_windspeed', 'hour_bef_humidity', 'hour_bef_visibility',
       'hour_bef_ozone', 'hour_bef_pm10', 'hour_bef_pm2.5', 'count',
       'visibility_pm10'],
      dtype='object')

In [126]:
train

id  hour  hour_bef_temperature  hour_bef_precipitation  \
0        3    20                  16.3                     1.0   
1        6    13                  20.1                     0.0   
2        7     6                  13.9                     0.0   
3        8    23                   8.1                     0.0   
4        9    18                  29.5                     0.0   
5       13     2                  13.6                     0.0   
6       14     3                  10.6                     0.0   
7       16    21                  16.0                     0.0   
8       19     9                  13.8                     0.0   
9       20    14                  17.2                     0.0   
10      21     4                   5.7                     0.0   
11      22    10                  15.4                     0.0   
12      24     9                  14.1                     0.0   
13      27    10                   9.2                     0.0   
14      28     1                  20.0                     0.0   
15      29    13                  14.0                     1.0   
16      30    21                  18.8                     0.0   
17      32    17                  11.5                     1.0   
18      33    13                  22.6                     0.0   
19      34    18                  18.0                     1.0   
20      35    10                  15.4                     0.0   
21      36     8                  12.6                     0.0   
22      37    16                  19.4                     0.0   
23      38    23                  15.4                     0.0   
24      44     3                  17.2                     0.0   
25      45     0                  11.7                     0.0   
26      46     2                  13.0                     0.0   
27      47     7                  10.9                     0.0   
28      48    15                  18.0                     0.0   
29      49     2                   8.9                     0.0   
...    ...   ...                   ...                     ...   
1429  2140    22                  14.1                     0.0   
1430  2142    17                  29.2                     0.0   
1431  2144     3                  17.4                     0.0   
1432  2150     7                  12.4                     0.0   
1433  2151     5                  19.0                     0.0   
1434  2152    20                  14.0                     0.0   
1435  2153    15                  27.4                     0.0   
1436  2154    18                  20.3                     0.0   
1437  2155     0                  12.3                     0.0   
1438  2156    15                  20.2                     0.0   
1439  2157    14                  28.4                     0.0   
1440  2158    23                  18.2                     0.0   
1441  2159    21                  14.8                     0.0   
1442  2160    21                  21.5                     0.0   
1443  2161     2                  11.4                     1.0   
1444  2162    23                  14.5                     0.0   
1445  2163    20                  21.5                     0.0   
1446  2164     2                   9.2                     0.0   
1447  2167    15                  26.3                     0.0   
1448  2168    19                  10.6                     0.0   
1449  2169     4                  10.2                     0.0   
1450  2170    15                  23.1                     0.0   
1451  2171     3                  18.1                     0.0   
1452  2172     4                   8.7                     0.0   
1453  2173    18                  24.8                     0.0   
1454  2174     4                  16.8                     0.0   
1455  2175     3                  10.8                     0.0   
1456  2176     5                  18.3                     0.0   
1457  2178    21                  20.7          

In [127]:
input_var = ['id', 'hour', 'hour_bef_temperature', 'hour_bef_precipitation',
       'hour_bef_windspeed', 'hour_bef_humidity', 'hour_bef_visibility',
       'hour_bef_ozone', 'hour_bef_pm10', 'hour_bef_pm2.5', 'visibility_pm10']

target = 'count'

In [129]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=1000, max_features=7)

In [130]:
rf.fit(train[input_var].fillna(0),train[target])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features=7, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [131]:
#test['temp_humid'] = test['hour_bef_temperature']/test['hour_bef_humidity']
test['visibility_pm10'] = test['hour_bef_visibility']/test['hour_bef_pm10']
#test['visibility_pm2.5'] = test['hour_bef_visibility']/test['hour_bef_pm2.5']

In [132]:
prediction_rf=rf.predict_proba(test[input_var].fillna(0))[:,1]
#랜덤포레스트 데이터를 이용하여 test데이터를 예측.
#학습은 랜덤포레스트로 시킨 것이다.
import xgboost as xgb
xgb_param={'objective':'reg:linear',
          'metric':'rmse',
          'max_depth':6,
          'eta':0.03,
          'min_child_samples':100}
#xgboost로 학습하기 위해.

In [133]:
from sklearn.model_selection import KFold
folds =KFold(n_splits=5,shuffle=True)

In [134]:
prediction_xgb=np.zeros(len(test))
#xgboost로 학습.
for fold_, (trn_idx,val_idx) in enumerate(folds.split(train[input_var].values,train[target].values)):
    trn_data=xgb.DMatrix(train[input_var].iloc[trn_idx],train[target].iloc[trn_idx])
    val_data=xgb.DMatrix(train[input_var].iloc[val_idx],train[target].iloc[val_idx])
    
    num_tree=10000
    
    xgb_model=xgb.train(xgb_param,
                     trn_data,
                     num_tree,
                     [(trn_data,'train'),(val_data,'valid')],verbose_eval=0,
                     early_stopping_rounds=100)
    prediction_xgb+=xgb_model.predict(xgb.DMatrix(test[input_var]),ntree_limit=xgb_model.best_ntree_limit)

prediction_xgb=prediction_xgb/5

[23:26:42] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:26:43] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:26:45] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:26:47] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:26:49] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [135]:
final=pd.DataFrame({'pred_xgb':prediction_xgb,'pred_rf':prediction_rf})
final.head()

pred_xgb  pred_rf
0   99.440785    0.000
1  203.412793    0.000
2   69.734885    0.044
3   41.279790    0.000
4   65.721683    0.071

In [136]:
final['pred_final'] = final['pred_xgb']/2+final['pred_rf']/2

In [137]:
pd.DataFrame({'id':test['id'], 'count':final['pred_xgb']}).to_csv("submission.csv", index = False)

In [138]:
final.head()

pred_xgb  pred_rf  pred_final
0   99.440785    0.000   49.720393
1  203.412793    0.000  101.706396
2   69.734885    0.044   34.889442
3   41.279790    0.000   20.639895
4   65.721683    0.071   32.896341

In [139]:
folds=KFold(n_splits=5,shuffle=True)

In [140]:
oof_rf=np.zeros(len(train))

prediction_rf=np.zeros(len(test))

for fold_, (trn_idx,val_idx) in enumerate(folds.split(train[input_var].values,train[target].values)):
    rf.fit(train[input_var].iloc[trn_idx].fillna(0),train[target].iloc[trn_idx])
    oof_rf[val_idx]=rf.predict_proba(train[input_var].fillna(0).iloc[val_idx])[:,1]
    prediction_rf+=rf.predict_proba(test[input_var].fillna(0))[:,1]

prediction_rf=prediction_rf/5

In [141]:
prediction_rf

array([0.0004, 0.    , 0.0486, 0.    , 0.058 , 0.    , 0.0004, 0.    ,
       0.0002, 0.0194, 0.    , 0.    , 0.0002, 0.    , 0.0002, 0.0002,
       0.001 , 0.0158, 0.    , 0.    , 0.    , 0.0022, 0.002 , 0.0004,
       0.    , 0.0002, 0.0368, 0.    , 0.    , 0.001 , 0.    , 0.    ,
       0.    , 0.    , 0.    , 0.0004, 0.0006, 0.012 , 0.    , 0.001 ,
       0.0004, 0.    , 0.    , 0.0038, 0.    , 0.    , 0.0132, 0.    ,
       0.0006, 0.    , 0.    , 0.    , 0.0012, 0.0152, 0.    , 0.    ,
       0.0004, 0.    , 0.0252, 0.0036, 0.0006, 0.0006, 0.0016, 0.    ,
       0.    , 0.    , 0.0024, 0.0002, 0.001 , 0.    , 0.0002, 0.0002,
       0.0004, 0.002 , 0.    , 0.    , 0.0174, 0.0004, 0.    , 0.0024,
       0.0002, 0.    , 0.0034, 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    , 0.0022, 0.0004, 0.    , 0.0014, 0.    , 0.    ,
       0.0014, 0.003 , 0.    , 0.    , 0.0152, 0.0002, 0.0034, 0.0002,
       0.0012, 0.0544, 0.0002, 0.002 , 0.0002, 0.017 , 0.    , 0.    ,
      

In [142]:
oof_xgb=np.zeros(len(train))

prediction_xgb=np.zeros(len(test))

for fold_, (trn_idx,val_idx) in enumerate(folds.split(train[input_var].values,train[target].values)):
    trn_data=xgb.DMatrix(train[input_var].iloc[trn_idx],train[target].iloc[trn_idx])
    val_data=xgb.DMatrix(train[input_var].iloc[val_idx],train[target].iloc[val_idx])
    num_tree=10000
    xgb_model=xgb.train(xgb_param,
                     trn_data,
                     num_tree,
                     [(trn_data,'train'),(val_data,'valid')],verbose_eval=0,
                     early_stopping_rounds=100)
    oof_xgb[val_idx]=xgb_model.predict(xgb.DMatrix(train[input_var].iloc[val_idx]),ntree_limit=xgb_model.best_ntree_limit)
    prediction_xgb+=xgb_model.predict(xgb.DMatrix(test[input_var]),ntree_limit=xgb_model.best_ntree_limit)
prediction_xgb=prediction_xgb/5

[23:31:56] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:31:58] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:32:02] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:32:04] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[23:32:05] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [143]:
oof_rf

array([0.023, 0.   , 0.004, ..., 0.   , 0.   , 0.   ])

In [144]:
oof_xgb

array([ 65.1027832 , 120.86112976,  13.84511948, ...,  23.35144043,
       232.48722839, 188.64613342])

In [145]:
pd.DataFrame({'oof_rf':oof_rf, 'oof_xgb':oof_xgb, 'count':train['count']})

oof_rf     oof_xgb  count
0      0.023   65.102783   49.0
1      0.000  120.861130  159.0
2      0.004   13.845119   26.0
3      0.002   63.722900   57.0
4      0.000  227.521759  431.0
5      0.000   31.908369   39.0
6      0.000   21.061361   23.0
7      0.000  114.187576  146.0
8      0.004   60.719715   39.0
9      0.001  123.818680   83.0
10     0.003   14.192064    6.0
11     0.001   58.329975   42.0
12     0.005   98.130867   59.0
13     0.000   63.382767   60.0
14     0.000   79.837013   74.0
15     0.140   36.485867    5.0
16     0.000  182.008194  217.0
17     0.079   31.238916   64.0
18     0.000  131.524902  208.0
19     0.017  119.143456   15.0
20     0.000   57.439953   58.0
21     0.003  113.704765  209.0
22     0.000  193.476135  122.0
23     0.004   72.857864   87.0
24     0.000   28.319267   30.0
25     0.000   64.282578   34.0
26     0.000   27.035789   29.0
27     0.000   69.750961   18.0
28     0.001  126.290733  106.0
29     0.000   15.697767   10.0
...      ...         ...    ...
1429   0.003  129.885193  144.0
1430   0.000  253.462143  324.0
1431   0.001   32.717625   31.0
1432   0.000   62.254951  104.0
1433   0.001   22.582291   14.0
1434   0.000  128.842804  150.0
1435   0.000  186.168030  218.0
1436   0.000  280.019653  242.0
1437   0.000   53.774158   66.0
1438   0.001  131.844818  105.0
1439   0.000  182.554138  179.0
1440   0.000  136.230530  141.0
1441   0.000  149.905319  120.0
1442   0.000  212.250717  239.0
1443   0.001   15.482450    5.0
1444   0.000  111.004135  119.0
1445   0.002  196.872345  201.0
1446   0.001   20.279985   24.0
1447   0.000  179.229095  272.0
1448   0.000   89.900131  114.0
1449   0.002   15.053752   11.0
1450   0.000  160.475204  266.0
1451   0.000   22.145359   26.0
1452   0.001    9.624918    8.0
1453   0.000  288.622589  303.0
1454   0.001   16.430496   21.0
1455   0.010   19.280010   20.0
1456   0.000   23.351440   22.0
1457   0.000  232.487228  216.0
1458   0.000  188.646133  170.0

[1459 rows x 3 columns]

In [146]:
train_super=pd.DataFrame({'oof_rf':oof_rf,'oof_xgb':oof_xgb,'count':train['count']})
test_super=pd.DataFrame({'pred_rf':prediction_rf,'pred_xgb':prediction_xgb})

In [147]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(train_super[['oof_rf','oof_xgb']], train_super['count'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [148]:
lr.predict(test_super[['pred_rf', 'pred_xgb']])

array([101.69999051, 199.74041602,  64.73964166,  42.78515742,
        55.08333712, 132.80216582, 243.26002176, 236.44309729,
        37.81400467, 139.14983708, 287.22684542, 234.24149301,
        96.40082651,  49.71957516, 180.93929528, 153.35227462,
        28.9531809 , 173.20317729, 342.16564659, 170.13379917,
       230.0416603 ,  87.18049499,  22.9597856 , 136.86152871,
       131.31150329, 104.19154833,  25.45349696, 118.20693451,
       118.15174671, 151.6119118 ,  70.99644237,  35.00801636,
        69.69972767, 116.98852129, 273.79103745,  35.20055638,
       127.46584611, 137.20566413, 209.26086509,  74.86508577,
        48.24682916, 116.86388753, 175.82794813,  72.40009785,
       303.6051874 , 194.07414496,  95.0135935 ,  64.03028921,
        26.4357254 ,  90.38953682, 242.38064805,  97.67558215,
       107.58005637,  85.49751533, 197.93237231, 158.21107355,
        52.09126893, 181.41338499,  24.65839892,  25.30788511,
        93.94254256,  85.95946596, 269.58474323, 263.21

In [149]:
final_predictions = lr.predict(test_super[['pred_rf', 'pred_xgb']])

In [150]:
pd.DataFrame({'id':test['id'], 'count':final_predictions}).to_csv("submission.csv",index=False)
